name: Generate version
on:
  pull_request:
    branches:
      - master

jobs:
  versionist:
    name: Versionist
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versionist.outputs.version }}
      updated: ${{ steps.versionist.outputs.updated }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run versionist
      id: versionist
      uses: bartversluijs/versionist-gh@master
      with:
        commit: false

