name: Generate version
on:
  push:
    branches:
      - master

jobs:
  versionist:
    name: Versionist
    if: "!contains(github.event.head_commit.author.name, 'bartversluijs')"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versionist.outputs.version }}
      updated: ${{ steps.versionist.outputs.updated }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run versionist
      id: versionist
      uses: ./test
      with:
        # Provide your versionist service account details
        commit: true
        github_email: 'bartv@nexelit.io'
        github_username: 'bartversluijs'
        github_token: ${{ secrets.GH_VERSIONIST_TOKEN }}

  dockerhub:
    name: Publish Docker image to Dockerhub
    needs: versionist
    if: "needs.versionist.outputs.updated == 'true'"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: bartversluijs
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          bartversluijs/versionist-gh:${{ needs.versionist.outputs.version }}
          bartversluijs/versionist-gh:latest

